#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#	Display "FizzBuzz" when the number is a multiple of 3 and 5
#	Display "Fizz" when the nuber [D[D[D[Dmber is a multiple of 3.
#	Display "Buzz" when the number is a multiple of 5.
#	Otherwise, displays the number.

for num in {1
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif ((num % 3 == 0 ))
	then
		echo "Fizz"
	else (( num % 5 == 0 ))
		[A[D[D[Dif[B[D[D[D[Dthen
		echo Buzz"[D[D[D[D[D"Buzz"
	else
		echo "$num"
	fi
done
