#!/usr/bin/env bash
# Desplay[D[D[D[D[i[C[C[C[C[C[C[C[C[C[C[C[D[D[D[D[D[Ds "Best School" 10 times using a while loop.

count=0

while [ $count -lt 10 ]
do
	echo "Best School"
	(( count++ ))
done
