#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.[D[D[D[Duntil[C[C[C[C[C[C[C[C[C[D[D[D

count=0

until [$count[D[D[D[D[D[D [C[C[C[D[D[D$[3~[3~[3~[3~[3~[C [ $count -eq 10 ]
do
	echo "Best School"
	(( count++ ))
done
