#!/usr/bin/env bash
# Display numbers from 1 to 20 in addition to:
#	"bad" luck from China"[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[C[3~[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C luck from China" for the 4th iteration
#	"bad luck from Japan" for the 9th iteration
#	"bad luck from Italy" for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4")echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
[C[C[C[D[D[D[D[D[D[D[D"17") echo "bad luck from Italy";;
	esac
	((count++))
done
