#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes
#	Diplay[D[D[D[Dsplay hours from 0 to 12
[D[D[D[D[D[D[D[D[D[D[D#	Display minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute ))
	doe
[A[C[C[C[C[Dne
	(( hour++ ))
done
