#!/usr/bin/env bash

sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf
service nginx restart
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
